import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import ScreenBackground from '../../components/ScreenBackground';
import SubScreenHeader from '../../components/SubScreenHeader';
import { colors, spacing, typography } from '../../theme/theme';

export default function TermsScreen({ navigation }) {
  return (
    <ScreenBackground>
      <SubScreenHeader title="Terms of Service" onBack={() => navigation.goBack()} />
      <ScrollView contentContainerStyle={styles.container}>
        <Text style={styles.updated}>Last updated: 2026</Text>

        <Text style={styles.heading}>1. Acceptance of Terms</Text>
        <Text style={styles.paragraph}>
          By using KLARIUM AI, you agree to these terms. If you are under 18, please
          use this app with the awareness of a parent or guardian.
        </Text>

        <Text style={styles.heading}>2. What KLARIUM AI Does</Text>
        <Text style={styles.paragraph}>
          KLARIUM AI is an educational tutoring app that uses Google's Gemini AI to
          explain NCERT/CBSE topics for Classes 1–12. It requires you to provide your
          own free Gemini API key to function.
        </Text>

        <Text style={styles.heading}>3. AI-Generated Content</Text>
        <Text style={styles.paragraph}>
          Answers are generated by AI and may occasionally be incomplete or contain
          mistakes. Always cross-check important information with your teacher or
          textbook.
        </Text>

        <Text style={styles.heading}>4. Your API Key</Text>
        <Text style={styles.paragraph}>
          Your Gemini API key is stored only on your device. Usage of that key
          (including any costs, if you enable billing on your Google account) is your
          responsibility.
        </Text>

        <Text style={styles.heading}>5. Acceptable Use</Text>
        <Text style={styles.paragraph}>
          Please use KLARIUM AI only for learning purposes. Do not use it to ask for
          or generate harmful, inappropriate, or dishonest content.
        </Text>

        <Text style={styles.heading}>6. Changes to These Terms</Text>
        <Text style={styles.paragraph}>
          We may update these terms as the app evolves. Continued use of the app means
          you accept the current terms.
        </Text>

        <Text style={styles.heading}>7. Contact</Text>
        <Text style={styles.paragraph}>
          Questions about these terms can be sent to klariumai@gmail.com.
        </Text>
      </ScrollView>
    </ScreenBackground>
  );
}

const styles = StyleSheet.create({
  container: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  updated: {
    ...typography.caption,
    marginBottom: spacing.md,
  },
  heading: {
    ...typography.h2,
    fontSize: 16,
    marginTop: spacing.lg,
    marginBottom: spacing.xs,
    color: colors.gold,
  },
  paragraph: {
    ...typography.body,
    lineHeight: 21,
  },
});
